apiVersion: apps/v1
kind: Deployment
metadata:
  name: gagan-deployment
  labels:
    app: gaganapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gaganapp
  template:
    metadata:
      labels:
        app: gaganapp
    spec:
      containers:
      - name: gagan-container
        image: gagandeepthinknyx/intel-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gaganapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: gaganapp 
