# Workflow to deploy the artifacts
name: cd
on: push

jobs:
  deploy:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v4.1.1
       
       - name: Deployment using kubernetes
         run: |
           sudo ansible-playbook -i /root/inv play.yml
